name: Export Secrets to TXT

on:
  workflow_dispatch: # 允许在 Actions 页面手动触发

jobs:
  export-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Write Secrets to File
        # 将 secrets 映射为环境变量
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WECHAT_WEBHOOK_KEY: ${{ secrets.WECHAT_WEBHOOK_KEY }}
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          SERVERCHAN_SCKEY: ${{ secrets.SERVERCHAN_SCKEY }}
          SERVERCHAN3_SCKEY: ${{ secrets.SERVERCHAN3_SCKEY }}
          COOLPUSH_SKEY: ${{ secrets.COOLPUSH_SKEY }}
          CUSTOM_WEBHOOK: ${{ secrets.CUSTOM_WEBHOOK }}
        # 将环境变量的值追加写入到 secrets.txt 中
        run: |
          echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> secrets.txt
          echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID" >> secrets.txt
          echo "WECHAT_WEBHOOK_KEY=$WECHAT_WEBHOOK_KEY" >> secrets.txt
          echo "DINGTALK_WEBHOOK=$DINGTALK_WEBHOOK" >> secrets.txt
          echo "PUSHPLUS_TOKEN=$PUSHPLUS_TOKEN" >> secrets.txt
          echo "SERVERCHAN_SCKEY=$SERVERCHAN_SCKEY" >> secrets.txt
          echo "SERVERCHAN3_SCKEY=$SERVERCHAN3_SCKEY" >> secrets.txt
          echo "COOLPUSH_SKEY=$COOLPUSH_SKEY" >> secrets.txt
          echo "CUSTOM_WEBHOOK=$CUSTOM_WEBHOOK" >> secrets.txt

      - name: Upload secrets.txt as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-exported-secrets
          path: secrets.txt
          retention-days: 1 # 设置保留时间为1天（最短时间），降低泄露风险
